# travis does not offer python container for OSX or Windows, not sure if we can get automated testing?
os: linux
language: python
python:
  - "3.6"
dist: bionic
install:
  - pip install -r requirements.txt
script: ./test.sh
