#!/usr/bin/env bash
#########################################################################
# __               __          __   __        ___ __
#|  |--.-----.----|  |--.-----|  |_|  .--.--.'  _|  |_.--.--.--.--------.
#|     |  -__|   _|  _  |__ --|   _|  |  |  |   _|   _|  |  |  |        |
#|__|__|_____|__| |_____|_____|____|__|_____|__| |____|________|__|__|__|
#########################################################################

hc() {
    herbstclient "$@"
}

hc emit_hook reload

export config=~/.config
# multi-monitor config, script by arandr
~/.screenlayout/HDMI+DP.sh

# remove all existing keybindings
hc keyunbind --all

#######################################
# keybindings			              #
#######################################
Mod=Mod4 # Use the super key as the main modifier

hc keybind $Mod-Shift-q spawn rofi -show menu \
    -modi "menu:rofi-power-menu \
    --choices=shutdown/reboot/lockscreen/logout" \
    -config $config/rofi/rofidmenu.rasi \
    -font "Droid 14"
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-q close_and_remove

# spawn kitty, my terminal emulator
hc keybind $Mod-Return spawn kitty

# spawn thunar, file manager
hc keybind $Mod-e spawn thunar

# spawn firefox
hc keybind $Mod-w spawn firefox

# spawn rofi, application launcher
hc keybind $Mod-d spawn rofi -modi drun -show drun \
    -config $config/rofi/rofidmenu.rasi \
    -font "Droid 14"

hc keybind $Mod-Shift-m spawn rofi -modi windowcd,window -show windowcd \
    -config $config/rofi/rofidmenu.rasi \
    -font "Droid 14"

# increase/decrease gaps
# frame gaps
hc keybind $Mod-minus spawn $config/herbstluftwm/changegaps.sh decrease frame 5
hc keybind $Mod-equal spawn $config/herbstluftwm/changegaps.sh increase frame 5
# window gaps
hc keybind $Mod-Shift-minus spawn $config/herbstluftwm/changegaps.sh decrease window 5
hc keybind $Mod-Shift-equal spawn $config/herbstluftwm/changegaps.sh increase window 5

#######################################
# basic window manipulation
#######################################
# focusing clients
hc keybind $Mod-Left focus left
hc keybind $Mod-Down focus down
hc keybind $Mod-Up focus up
hc keybind $Mod-Right focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified
# direction and focus new frame
hc keybind $Mod-v chain , split bottom 0.5 , focus down
hc keybind $Mod-h chain , split right 0.5 , focus right

# split and move focused window to the new frame
hc keybind $Mod-Shift-v chain , split bottom 0.5 , shift down
hc keybind $Mod-Shift-h chain , split right 0.5 , shift right

# mirror *across* x/y axis
hc keybind $Mod-y mirror horizontal
hc keybind $Mod-x mirror vertical

# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-Left resize left +$resizestep
hc keybind $Mod-Control-Down resize down +$resizestep
hc keybind $Mod-Control-Up resize up +$resizestep
hc keybind $Mod-Control-Right resize right +$resizestep

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc set focus_follows_mouse 1

# focus
hc keybind $Mod-BackSpace cycle_monitor
hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

#######################################
# tags
#######################################
tag_names=({1..5})
tag_keys=({1..5})

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}"; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ]; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma use_index -1 --skip-visible

#######################################
# layouting
#######################################
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-s set_attr clients.focus.floating toggle
hc keybind $Mod-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space \
    or , and . compare tags.focus.curframe_wcount = 2 \
    . cycle_layout +1 vertical horizontal max vertical grid \
    , cycle_layout +1

#######################################
# appearance
#######################################
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# Frame settings
hc attr settings.always_show_frame off
hc attr settings.frame_border_width 0
hc attr settings.frame_bg_transparent on
hc attr settings.frame_gap 40

hc attr settings.frame_border_active_color '#134e2c'
hc attr settings.frame_border_normal_color '#0b2e23'
hc attr settings.frame_active_opacity 100
hc attr settings.frame_normal_opacity 0

# Title bar
hc attr theme.title_height 0
hc attr theme.title_font 'Droid:pixelsize=16'
hc attr theme.padding_top 0 # space below the title's baseline (i.e. text depth)
hc attr theme.active.title_color '#EEEEEE'
hc attr theme.normal.title_color '#AAAAAA'

# Window borders
hc attr theme.border_width 5
hc attr theme.outer_width 0
# hc attr theme.active.outer_width 2 # only active windows have an outer border
hc attr theme.inner_width 2

hc attr theme.active.color '#0b2e23'
hc attr theme.normal.color '#171717'
hc attr theme.urgent.color '#d76c6c'

hc attr theme.active.inner_color '#134e2c'
hc attr theme.normal.inner_color '#323232'
hc attr theme.urgent.inner_color '#cc4444'

# copy inner color to outer_color
for state in active urgent normal; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

#######################################
# rules
#######################################
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'
hc unlock
hc detect_monitors
hc set auto_detect_monitors 1

#######################################
# panel
#######################################
~/.config/polybar/launch.sh

# User autostart commands go here
# wallpaper
nitrogen --restore

# compositor
picom &

# mic filters
easyeffects --gapplication-service &

# script to hide bar automatically polybar-hdmi_HDMI-1
# sleep 1
hideIt.sh --name '^polybar-dp_DP-1' --hover --direction top -s .4 &
hideIt.sh --name '^polybar-hdmi_HDMI-1$' --hover --direction top -s .4 &
